name: New Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  crosscheck:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Tests
        run: pytest -sv

  docs:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.8.3"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: crosscheck
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Setup Latest Poetry
        run: pipx install --suffix @main 'poetry @ git+https://github.com/python-poetry/poetry'
      - name: Install django-payments-chile
        run: poetry@main install --all-extras --all-groups
      - name: Deploy Docs
        run: poetry@main run mkdocs gh-deploy --force

  pypi-publish:
    name: Build and Upload
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.8.3"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: crosscheck
    environment:
      name: pypi
      url: https://pypi.org/p/khipu-tools
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v3
      - name: Setup Latest Poetry
        run: pipx install --suffix @main 'poetry @ git+https://github.com/python-poetry/poetry'
      - name: Install khipu-tools
        run: poetry@main install --all-extras --all-groups
      - name: Build khipu-tools
        run: poetry@main build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
